/* AUTO-GENERATED by ml/train_ranker.py — do not edit by hand. */
export interface RankerModel {
  readonly features: readonly string[];
  readonly mean: readonly number[];
  readonly std: readonly number[];
  readonly weights: readonly number[];
  readonly bias: number;
  readonly metrics: Readonly<Record<string, number>>;
}

export const RANKER_MODEL: RankerModel = {
  features: ["log_price", "rating", "log_reviews", "distance_km", "stars", "popularity", "free_cancellation", "breakfast"],
  mean: [8.481646, 8.028831, 5.511165, 4.394801, 3.349946, 0.303971, 0.550508, 0.635138],
  std: [0.695221, 1.044543, 0.948113, 3.108232, 1.061696, 0.167935, 0.497442, 0.481392],
  weights: [-0.915571, 0.579454, 0.179496, -0.428953, -0.151869, 0.115263, 0.128516, 0.108183],
  bias: -2.66135,
  metrics: {
    "ndcg@10_model": 0.8311,
    "ndcg@10_price_asc": 0.5642,
    "ndcg@10_rating_desc": 0.6665,
    "ndcg@10_random": 0.4745,
    "test_logloss": 0.2704,
    "test_auc": 0.7414,
    "train_sessions": 40000,
    "test_sessions": 10000,
    "candidates_per_session": 20,
    "booking_rate": 0.0898,
    "lift_vs_price_sort_pct": 47.2983,
    "lift_vs_rating_sort_pct": 24.6907
},
};
